name: into_develop_workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: cache ktlint
        uses: actions/cache@v2
        with:
          path: ~/.cache/ktlint
          key: ktlint-0.42.1-${{ runner.os }}-main

      - name: install ktlint
        run: |
          if ! command -v ktlint &> /dev/null; then
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
          fi
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/
          ktlint --version

      - name: run Ktlint
        continue-on-error: true
        run: |
          ktlint --relative . --reporter=plain --verbose

      - name: run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
