name: ktlint

on:
  pull_request:
    branches:
      - 'issue-**'

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
