name: Ktlint Check

on:
  pull_request:
    branches:
      - 'issue-**'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml || echo "Ktlint check failed."

      - name: Upload Ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: build/ktlint-report.xml
