name: Ktlint Check

on:
  pull_request:
    branches:
      - 'issue-**'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.0/ktlint
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/
          ktlint --version
        shell: bash

      - name: Run ktlint
        run: |
          ktlint --reporter=checkstyle | reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-review

        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
