name: test_issue_flow

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "test"
