name: test_issue_flow

on:
  project_card:
    - created
    - moved
    - converted
    - edited
    - deleted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "test"
